[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "resume-to-job-search-engine"
version = "0.1.0"
description = "A resume to job search engine project"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "python-dotenv==1.1.1",
    "pydantic[email]==2.11.7",
    "pydantic-settings==2.10.1",
    # "langchain==0.3.27",
    "langchain",
    "langchain-classic==1.0.0",
    # "langchain-community==0.3.27",
    "langchain-community",
    # "langchain-core==1.1.0",
    "langchain-google-genai",
    # "langchain-text-splitters==1.0.0",
    "google-genai==1.31.0",
    "pinecone==7.3.0",
    "pypdf==6.0.0",
    "streamlit==1.48.1",
    "pandas==2.3.2",
    "rank-bm25==0.2.2",
    "ragas",
]

[tool.setuptools]
packages = ["core", "streamlit", "utils"]
